// @ts-check
import { defineConfig } from 'astro/config';

export default defineConfig({
  site: 'https://cdot.world',
  // No integrations: this site ships zero client-side framework code. Every
  // script in the output is inline and hand-written - the theme switch, the
  // header menu, the two forms, the app gallery - plus public/assets/map.js.
  // None of it is bundled by Astro, so there is no client runtime in the output.
  // The sitemap is generated by src/pages/sitemap.xml.js rather than by
  // @astrojs/sitemap, to keep that true of the dependency list as well.
});
